version: '2.1'

services:

  l5d:
    image: buoyantio/linkerd:1.6.2
    volumes:
      - "./linkerd/config.yaml:/io.buoyant/linkerd.yaml:ro"
      - "./linkerd/disco:/io.buoyant/disco"
    ports:
      - "9990:9990"
      - "4140:4140"
    command: >
      /io.buoyant/linkerd.yaml

  # Audit events: App -> Flume -> Solr

  solr:
    image: solr:7
    ports:
      - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - gettingstarted

  flume:
    image: probablyfine/flume:latest
    environment:
      FLUME_AGENT_NAME: a1
    volumes:
      - ./flume.conf:/opt/flume-config/flume.conf:ro
      - ./log4j.properties:/opt/flume-config/log4j.properties:ro
    ports:
      - "5555:5555"

  # Distributed tracing

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "6831:6831/udp"

  # Spring's support infrastructure

  spring-config-server:
    container_name: 'spring-config-server'
    image: azul/zulu-openjdk:8
    volumes:
      - "./configuration-server/target/configuration-server-1.0.0.jar:/opt/app/configuration-server.jar:ro"
      - "./configuration-server/config-repo:/tmp/configuration-server/config-repo:rw"
    ports:
      - "8888:8888"
    command: ["java", "-jar", "/opt/app/configuration-server.jar"]

  spring-admin-server:
    container_name: 'spring-admin-server'
    image: azul/zulu-openjdk:8
    volumes:
      - "./admin-server/target/admin-server-1.0.0.jar:/opt/app/admin-server.jar:ro"
    ports:
      - "8099:8099"
    command: ["java", "-jar", "/opt/app/admin-server.jar"]

  graphit:
    container_name: "graphit"
    image: graphiteapp/graphite-statsd
    ports:
      - "8032:80"
      - "2003-2004:2003-2004"
#      - "2023-2024:2023-2024"
#      - "8125:8125/udp"
#      - "8126:8126"

  # Spring's applications

  service-time:
    container_name: 'service-time'
    image: azul/zulu-openjdk:8
    volumes:
      - "./service-time/target/service-time-1.0.0.jar:/opt/app/service-time.jar:ro"
    depends_on:
      - spring-config-server
    command: ["java", "-jar", "/opt/app/service-time.jar"]


  service-order:
    container_name: 'service-order'
    image: azul/zulu-openjdk:8
    volumes:
      - "./service-order/target/service-order-1.0.0.jar:/opt/app/service-order.jar:ro"
    environment:
        HTTP_PROXYHOST: l5d
        HTTP_PROXYPORT: 4140
    depends_on:
      - spring-config-server
    command: ["java", "-jar", "/opt/app/service-order.jar"]


  service-reservation:
    container_name: 'service-reservation'
    image: azul/zulu-openjdk:8
    volumes:
      - "./service-reservation/target/service-reservation-1.0.0.jar:/opt/app/service-reservation.jar:ro"
    depends_on:
      - spring-config-server
    command: ["java", "-jar", "/opt/app/service-reservation.jar"]

  # LOGGING SUBSYSTEM


  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:3
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.6/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:3.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp