admin:
  port: 9990
  ip: 0.0.0.0

namers:
  - kind: io.l5d.fs
    rootDir: /io.buoyant/disco

routers:
  - protocol: http
    dtab: |
      /svc => /#/io.l5d.fs
    servers:
      - port: 4140
        ip: 0.0.0.0