server:
  port: 8010

info:
  tags:
    environment: 'local'
    service: 'rest'

opentracing:
  jaeger:
    udp-sender:
      host: 'localhost'
      port: 6831

audit:
  flume:
    name: "agent007"
    enabled: true
    properties:
      channel.type: memory
      channel.capacity: 200
      sinks: sink1 sink2
      sink1.type: avro
      sink1.hostname: localhost
      sink1.port: 5555
      sink2.type: avro
      sink2.hostname: localhost
      sink2.port: 5555
      processor.type: failover
